UP:
  create_table:
    applications:
      name: [string, 255]
      slug: [string, 255]
    applications_releases:
      application_id: [11]
      release_id: [11]
    applications_tickets:
      application_id: [11]
      ticket_id: [11]
    comments:
      text: [text]
      ticket_id: [11]
      user_id: [11]
    groups:
      name: [string, 255]
      slug: [string, 255]
      queue_id: [11]
    priorities:
      name: [string, 255]
      slug: [string, 255]
    priorities_tickets:
      priorities_id: [11]
      tickets_id: [11]
    queues:
      name: [string, 255]
      slug: [string, 255]
      is_first_line: [boolean]
    releases:
      date_of: [datetime]
      slug: [string, 255]
    statuses:
      name: [string, 255]
      slug: [string, 255]
    tickets:
      name: [string, 255]
      slug: [string, 255]
      problem: [text]
      date_completed: [datetime]
      release_id: [11]
      status_id: [11]
      queue_id: [11]
    tickets_users:
      ticket_id: [11]
      user_id: [11]
    users:
      slug: [string, 255]
      username: [string, 255]
      password: [string, 40]
      group_id: [11]
DOWN:
  drop_table: [applications, applications_releases, applications_tickets, comments, groups, priorities, priorities_tickets, queues, releases, statuses, tickets, tickets_users, users]