UP:
  create_table:
    tickets:
      name: [string, 255]
      slug: [string, 255]
      problem: [text]
      is_complete: [boolean]
      application_id: [11]
      release_id: [11]
      queue_id: [11]
      user_id: [11]
DOWN:
  drop_table: tickets