UP:
    create_table:
        applications_releases:
            no_id: true
            application_id: [11]
            release_id: [11]
#        application_tickets:
#            application_id: [11]
#            ticket_id: [11]
#        tickets_users:
#            ticket_id: [11]
#            user_id: [11]
    drop_field:
        applications: [release_id, ticket_id]
#        releases: [ticket_id]
#        tickets: [application_id, user_id]
#        users: [ticket_id]
            
DOWN:
    add_fields:
        applications:
            ticket_id: [11]
            release_id: [11]
#        releases:
#            ticket_id: [11]
#        tickets:
#            application_id: [11]
#            user_id: [11]
#        users:
#            ticket_id: [11]
    drop_table: [applications_releases]