---
UP:
  create_table:
    applications:
      name:
        type: string
        length: 255
        not_null:
      slug:
        type: string
        length: 255
        not_null:
      ticket_id:
        type: integer
        length: 11
        not_null:
  
  create_table:
    groups:
      name:
        type: string
        length: 255
        not_null:
      slug:
        type: string
        length: 255
        not_null:
      queue_id:  
        type: integer
        length: 11
        not_null:
  create_table:
    releases:
      date_of:
        type: datetime
      slug:
        type: string
        length: 255
        not_null:
      ticket_id:
        type: integer
        length: 11
        not_null:
  create_table:
    tickets:
      name:
        type: string
        length: 255
        not_null:
      slug:
        type: string
        length: 255
        not_null:
      problem:
        type:
        not_null:
      is_complete:
        type: boolean
        length: 1
        not_null:
      application_id:
        type: integer
        length: 11
        not_null:
      release_id:
        type: integer
        length: 11
        not_null:
      queue_id:
        type: integer
        length: 11
        not_null:
      user_id:
        type: integer
        length: 11
        not_null:
  create_table:
    queues:
      name: 
        type: string
        length: 255
        is_null:
      slug:
        type: string
        length: 255
        is_null: 
      is_first_line: 
        type: boolean
        length: 1
        not_null:
  create_table:
    users:
      slug:
        type: string
        length: 255
        not_null:
      username:
        type: string
        length: 255
        not_null:
      password:
        type: string
        length: 40
        not_null:
      group_id:
        type: integer
        length: 11
        not_null:
      ticket_id:
        type: integer
        length: 11
        not_null:
DOWN:
    drop_table: applications
    drop_table: groups
    drop_table: releases
    drop_table: tickets
    drop_table: queues
    drop_table: users